on:
  pull_request: null
  push:
    branches:
      - 4.x

name: static analysis

permissions:
  contents: read

jobs:
  psalm:
    uses: spiral/gh-actions/.github/workflows/psalm.yml@master
    with:
      os: >-
        ['ubuntu-latest']
